name: Publish to NPM
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    # prevents this action from running on forks
    if: github.repository == 'chrishrb/techradar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js 21
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'pnpm'

      - name: Run install
        run: pnpm run ci

      - name: Run build
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Run test
        run: pnpm test

      - name: Run publish
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
